### ISSUE TITLE
建议默认按照发布日期排序

### ISSUE THREAD

**Issue by Victarry** [upupming/new-grad-positions#3]

**Comment by upupming** [comment]
@Victarry 在前端页面 https://upupming.site/new-grad-positions/ 中可以按照发布日期排序，但是现在没有支持多个条件的排序（例如先按照类型排序，类型相同的再按照发布日期排序），我过会会加上。

在 GitHub 的 README 里面，为了方便索引，采用的是公司名称拼音的字典序，个人感觉更方便一些。如果大家希望改成发布日期排序，可以在 @Victarry 的 comment 上点赞，我之后考虑改一下。

**Comment by Kaiyiwing** [comment]
🤔 我也建议是默认按照 `日期` + `降序` 的方式排序，方便迅速了解最新开招聘的外企

**Comment by upupming** [comment]
@Victarry @Kaiyiwing  感谢建议！我会将 README 改成日期降序的形式，然后前端页面我会在周末调整优化一下。

**Comment by Kaiyiwing** [comment]
🤔 我把日期和降序的 pr 提了，#7

**Comment by upupming** [comment]
感谢 @Kaiyiwing 的贡献，我已经对 UI 进行了优化，现在可以关闭此 issue 了，有新的建议欢迎再次提 issue！

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/24741764/179349748-f9a25856-3537-4c4b-ad88-95df9e68b07a.png">

**Comment by Kaiyiwing** [comment]
huo！ 大佬太肝啦

可以调整一下 hover 时的动画，放缓一些，现在有点生硬

![CleanShot 2022-07-16 at 18 04 21](https://user-images.githubusercontent.com/44634134/179350299-7db93c55-cd1a-477f-9be7-1f153e99dc37.gif)

**Comment by upupming** [comment]
@Kaiyiwing 专业！已经修改了动画效果，顺便加上了笔记功能，点击卡片即可对其做笔记（存在本地浏览器中）。

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/24741764/179354155-752b513f-3a50-491e-b1e6-dae5806353f1.png">
